// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATNEWWJiK1kX9N_Ok1Nikj5Od_kzpZHLY',
    appId: '1:1046726338655:web:227b3721c8f5320fa853ea',
    messagingSenderId: '1046726338655',
    projectId: 'nutrikmais',
    authDomain: 'nutrikmais.firebaseapp.com',
    storageBucket: 'nutrikmais.firebasestorage.app',
    measurementId: 'G-7TDNDJB1Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkXW0qiNq0wjUaYjJMVQHmKHQRXuffQao',
    appId: '1:1046726338655:android:8de004f0ca7a591ea853ea',
    messagingSenderId: '1046726338655',
    projectId: 'nutrikmais',
    storageBucket: 'nutrikmais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIw5tdPVzLUHLb7Q2vfNhFaRvACl3zlDE',
    appId: '1:1046726338655:ios:c5b8bd25a938148ba853ea',
    messagingSenderId: '1046726338655',
    projectId: 'nutrikmais',
    storageBucket: 'nutrikmais.firebasestorage.app',
    iosBundleId: 'com.nutrikmais.nutrikmais',
  );

}